const headerActions = {
    SET_SELECT_HEADER: 'HEADER.SET_SELECT_HEADER',
    SET_SHOW_HEADER: 'HEADER.SET_SHOW_HEADER',
    SET_HIDE_HEADER: 'HEADER.SET_HIDE_HEADER',
    SET_SHOW_LINK_AUTOMATA_TOOL: 'HEADER.SET_SHOW_LINK_AUTOMATA_TOOL',
    SET_HIDE_LINK_AUTOMATA_TOOL: 'HEADER.SET_HIDE_LINK_AUTOMATA_TOOL',
    SET_TITLE_HEADER: 'HEADER.SET_TITLE_HEADER',
}

export default headerActions